---
- name: Execute Ansible Roles on Linux Nodes
  hosts: "{{target_hosts}}"
  become: true
  gather_facts: yes
  roles:
    - datadisk-n01009389
    - profile-n01009389
    - user-n01009389
    - webserver-n01009389
