---
- name: Install Apache web server
  ansible.builtin.package:
    name: apache2
    state: present

- name: Create HTML files
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "/var/www/html/{{ item }}.html"
  loop:
    - vm1
    - vm2
    - vm3

- name: Set permissions on HTML files
  ansible.builtin.file:
    path: "/var/www/html/{{ item }}.html"
    mode: "0444"
  loop:
    - vm1
    - vm2
    - vm3
  notify: Restart Apache

- name: Ensure Apache is started and enabled
  ansible.builtin.service:
    name: apache2
    state: started
    enabled: yes

- name: Ensure Apache starts on boot
  ansible.builtin.service:
    name: apache2
    enabled: yes

handlers:
  - name: Restart Apache
    ansible.builtin.service:
      name: apache2
      state: restarted
